### ISSUE TITLE
Error when trying to run flow from GRR 3.3.0.8 (decoding error maybe?)

### ISSUE THREAD

**Issue by niemesrw** [keithtyler/autorun_hunter#1]
I'm not a developer so please bear with me. I have tried running the flow from my GRR instance and it's producing this error message:

Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_base.py", line 633, in RunStateMethod method(responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flows/general/administrative.py", line 357, in Done responses.status) FlowError: Execute Python hack failed: message FlowStatus { backtrace : u'Traceback (most recent call last):\n File "site-packages\\grr_response_client\\actions.py", line 141, in Execute\n File "site-packages\\grr_response_client\\client_actions\\standard.py", line 348, in Run\n File "<string>", line 2270, in <module>\n File "subprocess.py", line 390, in __init__\n File "subprocess.py", line 640, in _execute_child\nUnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\u2013\' in position 56: ordinal not in range(128)\n' client_id : u'C.1d8ab47457f0e870' cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u"UnicodeEncodeError('ascii', u'powershell.exe -NoProfile -ExecutionPolicy remotesigned \\u2013EncodedCommand DQAKAGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAiAGMAOgBcAHcAaQBuAGQAbwB3AHMAXAB0AGUAbQBwAFwAQQB1AHQAbwByAHUAbgBzAGMALgBlAHgAZQAiACkAIAB7AA0ACgAgACAAIAAgACAAIABjADoAXAB3AGkAbgBkAG8Adw\\nBzAFwAdABlAG0AcABcAEEAdQB0AG8AcgB1AG4AcwBjAC4AZQB4AGUAIAAvAGEAYwBjAGUAcAB0AGUAdQBsAGEAIAAtAGEAIAAqACAALQBjACAALQBoACAALQBtACAALQBzACAAJwAqACcAIAAtAG4AbwBiAGEAbgBuAGUAcgAgADIAPgAg\\nACQAbgB1AGwAbAB8ACAAQwBvAG4AdgBlAHIAdABGAHIAbwBtAC0AQwBzAHYAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewANAAoAIAAgACAAIAAgACAAIABpAGYAIAAoACQAXwAuACIAUwBIAEEALQAyADUANgAiAC\\nkAIAAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAaABhAHMAaAAgAD0AIAAkAF8ALgAiAFMASABBAC0AMgA1ADYAIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABsAG8AYwBhAHQAaQBvAG4AIAA9ACAAJABfAC4A\\nIgBFAG4AdAByAHkAIABMAG8AYwBhAHQAaQBvAG4AIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwAGEAdABoACAAPQAgACQAXwAuACIASQBtAGEAZwBlACAAUABhAHQAaAAiAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIA\\nAkAHMAaQBnAG4AZQByACAAPQAgACQAXwAuACIAUwBpAGcAbgBlAHIAIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ARQB2AGUAbgB0AEwAbwBnACAALQBMAG8AZwBOAGEAbQBlACAAIgBBAHAAcABsAGkAYwBh\\nAHQAaQBvAG4AIgAgAC0AUwBvAHUAcgBjAGUAIAAiAEcAUgBSACIAIAAtAEUAdgBlAG4AdABJAEQAIAA2ADAAMAAgAC0ARQBuAHQAcgB5AFQAeQBwAGUAIABJAG4AZgBvAHIAbQBhAHQAaQBvAG4AIAAtAE0AZQBzAHMAYQBnAGUAIAAiAG\\ngAYQBzAGgAPQAkAGgAYQBzAGgAIABMAG8AYwBhAHQAaQBvAG4APQAiACIAJABsAG8AYwBhAHQAaQBvAG4AIgAiACAAUABhAHQAaAA9ACIAIgAkAHAAYQB0AGgAIgAiACAAUwBpAGcAbgBlAHIAPQAiACIAJABzAGkAZwBuAGUAcgAiACIA\\nIgAgAC0AQwBhAHQAZQBnAG8AcgB5ACAAMQAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgAgACAAIAAgACAAIAAgAH0ADQAKAH0AIAANAAoAZQBsAHMAZQAgAHsAIABXAHIAaQB0AGUALQBFAHIAcgBvAHIAIAAiAEEAdQ\\nB0AG8AcgB1AG4AcwBjAC4AZQB4AGUAIABuAG8AdAAgAGYAbwB1AG4AZAAgAGkAbgAgAHQAbQBwAC4AIgB9AA0ACgA=', 56, 57, 'ordinal not in range(128)'): 'ascii' codec can't encode character u'\\u2013' in position 56: ordinal not in range(128)" flow_id : u'137E6D7F' network_bytes_sent : 2496 request_id : 1 response_id : 1 status : ERROR } 

When I try running it from the CLI using WSL see this:

python2 grr_autorun_hunter.py
  File "grr_autorun_hunter.py", line 2269
SyntaxError: Non-ASCII character '\xe2' in file grr_autorun_hunter.py on line 2269, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I'm not sure if it's related.

**Comment by keithtyler** [comment]
Looks like encoding, try encoding file (autorunscBinary) and "b64Powershell" script using this:

$file = "C:\temp\autorunsc.exe"
$data = get-content $file
$bytes = $bytes = [System.Text.Encoding]::UNICODE.GetBytes($data)
$encodedCommand = [Convert]::ToBase64String($bytes)

Then write the output of $encodedCommand to screen or file. Hope that helps.
